services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      # 掛載原始碼（不包含 node_modules）
      - ./frontend:/app
      # 使用 Docker 內的 node_modules
      - /app/node_modules